language: python

python:
    - "2.7"

sudo: false

addons:
  apt:
    packages:
      - hwloc

install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - unset PYTHONPATH
    - conda config --set always_yes yes 
    - conda config --add channels mikaem/label/test
    - conda config --add channels mikaem
    - conda install h5py=2.6.0 fenics=1.7.0 pyvtk mpi4py pytest boost=1.57.0
    - ls /usr/lib/x86_64-linux-gnu/

script:
    - py.test
