language: python

python:
    - "2.7"

sudo: false

install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - unset PYTHONPATH
    - conda config --set always_yes yes 
    - conda config --add channels mikaem/label/docker-conda-gcc
    - conda install h5py-parallel fenics=2016.1 pytest
    - instant-clean
    - ldd $HOME/miniconda/lib/libpetsc.so
    - ldd $HOME/miniconda/lib/libdolfin.so

after_failure:
    - cd $HOME/.instant/error
    - bash /home/travis/build/mikaem/testtravis/print_compilelog.sh
    
script:
    - py.test
