language: python

python:
    - "2.7"

sudo: false

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.9
   - g++-4.9

install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - unset PYTHONPATH
    - conda config --set always_yes yes 
    - conda config --add channels mikaem/label/dev
    - conda config --add channels mikaem
    - conda install h5py=2.6.0 fenics=1.7.0 pyvtk mpi4py hwloc pytest boost=1.57.0

script:
    - py.test
