package:
  name: testtravis
  version: "1.0"
  
source:
  git_url: ../../

build:
  number: 10

requirements:
  build:
    - python
    - fenics ==2016.2.dev
    - h5py-parallel
    

  run:
    - python
    - fenics ==2016.2.dev
    - h5py-parallel

test:
    requires:
      - pytest

